### ISSUE TITLE
Error on rake  redmine:plugins:migrate 

### ISSUE THREAD

**Issue by higkoo** [a-ono/redmine_per_project_formatting#9]
# rake redmine:plugins:migrate RAILS_ENV=production
```
Mysql2::Error: ALTER command denied to user 'ops'@'192.168.22.33' for table 'projects': ALTER TABLE `projects` ADD `text_formatting` varchar(255)/data/work/redmine/plugins/redmine_per_project_formatting/db/migrate/20130520022527_add_text_formatting_to_project.rb:3:in `change'
/data/work/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/work/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/work/redmine/lib/redmine/plugin.rb:459:in `each'
/data/work/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/work/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: ALTER command denied to user 'ops'@'172.18.20.22' for table 'projects': ALTER TABLE `projects` ADD `text_formatting` varchar(255)
/data/work/redmine/plugins/redmine_per_project_formatting/db/migrate/20130520022527_add_text_formatting_to_project.rb:3:in `change'
/data/work/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/work/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/work/redmine/lib/redmine/plugin.rb:459:in `each'
/data/work/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/work/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Mysql2::Error: ALTER command denied to user 'ops'@'172.18.20.22' for table 'projects'
/data/work/redmine/plugins/redmine_per_project_formatting/db/migrate/20130520022527_add_text_formatting_to_project.rb:3:in `change'
/data/work/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/work/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/work/redmine/lib/redmine/plugin.rb:459:in `each'
/data/work/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/work/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```  
# rake redmine:plugins:migrate RAILS_ENV=production --trace  
```
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating redmine_agile (Redmine Agile plugin (Light version))...
Migrating redmine_ckeditor (Redmine CKEditor plugin)...
Migrating redmine_code_review (Redmine Code Review plugin)...
Migrating redmine_issue_templates (Redmine Issue Templates plugin)...
Migrating redmine_per_project_formatting (Redmine per project formatting plugin)...
== 20130520022527 AddTextFormattingToProject: migrating =======================
-- add_column(:projects, :text_formatting, :string)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Mysql2::Error: ALTER command denied to user 'ops'@'192.168.22.33' for table 'projects': ALTER TABLE `projects` ADD `text_formatting` varchar(255)/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/data/work/redmine/plugins/redmine_per_project_formatting/db/migrate/20130520022527_add_text_formatting_to_project.rb:3:in `change'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/work/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/work/redmine/lib/redmine/plugin.rb:459:in `each'
/data/work/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/work/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: ALTER command denied to user 'ops'@'192.168.22.33' for table 'projects': ALTER TABLE `projects` ADD `text_formatting` varchar(255)
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/data/work/redmine/plugins/redmine_per_project_formatting/db/migrate/20130520022527_add_text_formatting_to_project.rb:3:in `change'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/work/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/work/redmine/lib/redmine/plugin.rb:459:in `each'
/data/work/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/work/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
Mysql2::Error: ALTER command denied to user 'ops'@'192.168.22.33' for table 'projects'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/data/work/redmine/plugins/redmine_per_project_formatting/db/migrate/20130520022527_add_text_formatting_to_project.rb:3:in `change'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/data/work/redmine/lib/redmine/plugin.rb:446:in `migrate'
/data/work/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/data/work/redmine/lib/redmine/plugin.rb:459:in `each'
/data/work/redmine/lib/redmine/plugin.rb:459:in `migrate'
/data/work/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by galupa** [comment]
Hi, not sure if you still have the issue, but based on the logs it seems the problem is the user does not have ALTER privilege
